apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "http-monitoring-system.labels" . | nindent 4 }}
data:
  MONITOR_INTERVAL: "{{ .Values.env.monitorInterval }}"
  APP_PORT: "{{ .Values.service.containerPort}}"
  DATABASE_MASTER_URL: "postgresql://{{ .Values.pg.username }}:{{ .Values.pg.password }}@postgres-primary-svc.default:5432/{{ .Values.pg.database }}"
  DATABASE_REPLICA_URL: "postgresql://{{ .Values.pg.username }}:{{ .Values.pg.password }}@postgres-replica-svc.default:5432/{{ .Values.pg.database }}"

