apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-monitoring-system-smon
  labels:
    release: http-monitoring-system
spec:
  selector:
    matchLabels:
      app: http-monitoring-system
  endpoints:
  - port: http
    interval: 10s
