apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: http-monitoring-system
    {{- include "http-monitoring-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.containerPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-app
