apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "http-monitoring-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: http-monitoring-system
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: {{ .Values.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /health/startup
            port: {{ .Values.service.port }}
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: MONITOR_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: MONITOR_INTERVAL
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: APP_PORT
        - name: DATABASE_MASTER_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: DATABASE_MASTER_URL
        - name: DATABASE_REPLICA_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: DATABASE_REPLICA_URL
