apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "http-monitoring-system.labels" . | nindent 4 }}
data:
  MONITOR_INTERVAL: "{{ .Values.env.monitorInterval }}"
  APP_PORT: "{{ .Values.service.containerPort}}"
  DATABASE_MASTER_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@http-monitoring-system-postgresql-primary.default:5432/{{ .Values.postgresql.auth.database }}"
  DATABASE_REPLICA_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@http-monitoring-system-postgresql-read.default:5432/{{ .Values.postgresql.auth.database }}"
