apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres
    role: primary
