replicaCount: 1

image:
  repository: feri80/http-monitoring-system
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 8000
  containerPort: 8000


env:
  monitorInterval: 1

postgresql:
  architecture: replication
  replicaCount: 1
  auth:
    database: monitor
    username: postgres
    password: password
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "13.0.0-debian-10-r0"
    pullPolicy: IfNotPresent


prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitors:
      - name: "http-monitoring-system"
        selector:
          matchLabels:
            app: "http-monitoring-system"
        endpoints:
          - port: "8000"
            interval: "30s"
            path: "/metrics"

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: LoadBalancer
