replicaCount: 1

image:
  repository: feri80/http-monitoring-system
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 8000
  containerPort: 8000

env:
  monitorInterval: 1

pg:
  database: monitor
  username: postgres
  password: password
  image: postgres:13-alpine

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitors:
      - name: "http-monitoring-system"
        selector:
          matchLabels:
            app: "http-monitoring-system"
        endpoints:
          - port: "http"
            interval: "30s"

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: LoadBalancer
